### ISSUE TITLE
Loading on a plain vanilla Win7 VM gives "Error loading file"

### ISSUE THREAD

**Issue by suterma** [suterma/Replayer#11]
When loading the demo compilation on a totally new Windows 7 machine (on Azure) the application starts up nicely, but when loading the compilation a "NoDriver calling acmFormatSuggest" error message pops up.

![2018-03-13 12_24_10-52 191 249 153 - remotedesktopverbindung](https://user-images.githubusercontent.com/11473920/37339168-00fdad66-26ba-11e8-8e92-491af48d26e0.png)
When dismissed, and tried to play, an NAudio Null-Reference exception occurs.

**Comment by suterma** [comment]
Details 
```
===================================

Object reference not set to an instance of an object. (NAudio)

------------------------------
Program Location:

   at NAudio.Wave.WaveOut.EnqueueBuffers()
   at NAudioDemo.AudioPlaybackDemo.AudioPlaybackPanel.set_State(MediaPlayerState value)
   at Replayer.WinForms.Ui.Views.Tracks.TracksPresenter.Tracks_DoubleClick(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnDoubleClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at DevExpress.Utils.Controls.ControlBase.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by suterma** [comment]
More info on https://stackoverflow.com/a/35638756/79485

**Comment by suterma** [comment]
This problem could likely get solved with NLayer, as proposed here: https://stackoverflow.com/a/45651276/79485

However, currently this will not get solved, as most user pc's most likely will have the codecs installed. If this turns out to be a blocker for many users, open again.
